/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-03 03:43:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.searchfree.common.ResourcePath;
import com.kh.searchfree.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1580404612000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1580152436000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.searchfree.member.model.vo.Member");
    _jspx_imports_classes.add("com.kh.searchfree.common.ResourcePath");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Directory</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .back-white{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-hei, .btn-hei:hover {\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            margin-bottom: 50px;\r\n");
      out.write("            background-color: #001d38;\r\n");
      out.write("            border: 0px  ;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-hei-line{\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            line-height: 15px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- header-start -->\r\n");
      out.write("\t");
      out.write("`\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String msg = (String)session.getAttribute("msg");
	Member loginMember = (Member)session.getAttribute("loginMember");
	// Object 타입이라서 형 변환 해줘야 함
	
	// C6) 쿠키사용을 위한 변수 생성
	boolean save = false; // 아이디 저장 체크박스
	String saveId = ""; // 쿠키에 저장된 saveId 라는 키가 가지고 있는 값을 저장할 변수
	Cookie[] cookies = request.getCookies(); // 전달받은 쿠키 저장
	
	// 서버 첫 시작시 request.getCookies()의 값이 null
	// -> if문으로 처리하지 않는 경우 페이지 로딩 시 NullPointException 발생됨
	if(cookies != null ){
		
		for(Cookie c : cookies){
			
			// 쿠키 객체에서 name을 얻어와 그 값이 "saveId"와 같은지 비교
			// 				== key, 속성
			if(c.getName().equals("saveId")){
				
				saveId = c.getValue();
				save = true;
				
			}
		}
	}
	
				

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\"\r\n");
      out.write("\t\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/style.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\t\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost:8080/searchfree/resources/img/favicon.png\" />\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS here -->\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/owl.carousel.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/magnific-popup.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/font-awesome.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/themify-icons.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/nice-select.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/flaticon.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/gijgo.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/animate.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/slick.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/searchfree/resources/css/slicknav.css\"/>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom fonts for this template-->\r\n");
      out.write("  <link href=\"http://localhost:8080/searchfree/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/html\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template-->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("      <!-- link that opens popup -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css\" />\r\n");
      out.write("      <!-- JS here -->\r\n");
      out.write("      \r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/popper.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/ajax-form.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/waypoints.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/scrollIt.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/wow.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/nice-select.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/plugins.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/gijgo.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/slick.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("      <!--contact js-->\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/contact.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.form.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/jquery.validate.min.js\"></script>\r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/mail-script.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("      <script src=\"http://localhost:8080/searchfree/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"modal-container-1207\" role=\"dialog\"\r\n");
      out.write("                                            aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                                            <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                                                <div class=\"modal-content\">\r\n");
      out.write("                                                    <div class=\"modal-header\">\r\n");
      out.write("                                                        <h5 class=\"modal-title\" id=\"myModalLabel\">Login</h5>\r\n");
      out.write("                                                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("                                                            <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"modal-body\">\r\n");
      out.write("                                                        <form class=\"form-signin\" method=\"POST\" action=\"");
      out.print( request.getContextPath());
      out.write("/member/login.do\"\r\n");
      out.write("                                                        onsubmit=\"return loginValidate();\">\r\n");
      out.write("                                                        <!-- form태그 내부에서 submit 이벤트가 발생했을 때 loginValidate() 실행, \r\n");
      out.write("                                                                  결과가 false가 나오면 return false가 되므로 갱신이벤트가 사라짐(페이지가 안 넘어감)-->\r\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"memberId\" name=\"memberId\"\r\n");
      out.write("                                                                placeholder=\"ID\" value=\"\"> <br> \r\n");
      out.write("                                                            <input type=\"password\" class=\"form-control\" id=\"memberPwd\" name=\"memberPwd\"\r\n");
      out.write("                                                                placeholder=\"password\"> \r\n");
      out.write("                                                                <br>\r\n");
      out.write("                                                                <div class=\"col-lg-3 col-md-4 mt-sm-30\">\r\n");
      out.write("                                                                <div class=\"switch-wrap d-flex justify-content-between\">\r\n");
      out.write("                                                                    <div class=\"primary-checkbox\">\r\n");
      out.write("                                                                        <input type=\"checkbox\" id=\"default-checkbox\">\r\n");
      out.write("                                                                        <label for=\"default-checkbox\"></label>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <h4>save id</h4>\r\n");
      out.write("                                                                </div></div>\r\n");
      out.write("                                                                <br>\r\n");
      out.write("                                                             <div class=\"text-center\">   \r\n");
      out.write("                                                             <button class=\"genric-btn success-border medium mt-3\" type=\"submit\">Login</button>\r\n");
      out.write("                                                            <!-- <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">Login</button> -->\r\n");
      out.write("                                                            <a class=\"genric-btn success-border medium mt-3\" href=\"");
      out.print(request.getContextPath() );
      out.write("/member/signUpForm.do\">Join us</a> \r\n");
      out.write("                                                            <a class=\"genric-btn success-border medium mt-3\"  href=\"#\">find ID / password</a>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"modal-footer\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("                                                            data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("    <!-- header-start -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"header-area\">\r\n");
      out.write("            <div id=\"sticky-header\" class=\"main-header-area \" style=\"padding: 10px;\">\r\n");
      out.write("                <div class=\"container-fluid \">\r\n");
      out.write("                    <div class=\"header_bottom_border\">\r\n");
      out.write("                        <div class=\"row align-items-center\">\r\n");
      out.write("                            <div class=\"col-xl-3 col-lg-2\">\r\n");
      out.write("                                <div class=\"logo\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <img src=\"http://localhost:8080/searchfree/resources/img/logo.png\" alt=\"\" >\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xl-6 col-lg-7\">\r\n");
      out.write("                                <div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("                                    <nav>\r\n");
      out.write("                                        <ul id=\"navigation\">\r\n");
      out.write("                                            <li><a href=\"index.html\">home</a></li>\r\n");
      out.write("                                            <li><a href=\"Listings.html\">Listings</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">pages <i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                                <ul class=\"submenu\">\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    <li><a href=\"elements.html\">elements</a></li>\r\n");
      out.write("                                                    <li><a href=\"single_listings.html\">Single listing</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a href=\"about.html\">about</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">blog <i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                                <ul class=\"submenu\">\r\n");
      out.write("                                                    <li><a href=\"blog.html\">blog</a></li>\r\n");
      out.write("                                                    <li><a href=\"single-blog.html\">single-blog</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a href=\"\">공지사항</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </nav>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xl-3 col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                            ");
 if(loginMember == null) {
      out.write("\r\n");
      out.write("                                <div class=\"Appointment\">\r\n");
      out.write("                                    <div class=\"book_btn d-none d-lg-block\" >\r\n");
      out.write("                                        <a id=\"modal-1207\" href=\"#modal-container-1207\" role=\"button\"\r\n");
      out.write("                                            class=\"danger radius btn-hei-line\" data-toggle=\"modal\">로그인</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
} else if(loginMember.getMemberGrade() == '3' && loginMember.getMemberStatus() == 'N'){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-end align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(loginMember.getMemberNm());
      out.write("님 환영합니다. &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/main\" role=\"button\" class=\"btn btn-sm btn-outline-secondary\">관리자 페이지</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/logout.do\" role=\"button\" class=\"btn btn-sm btn-outline-secondary\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- header-end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- slider_area_start -->\r\n");
      out.write("    <div class=\"slider_area \">\r\n");
      out.write("        <div class=\"single_slider  d-flex align-items-center slider_bg_1\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-10\">\r\n");
      out.write("                        <div class=\"slider_text text-center justify-content-center\">\r\n");
      out.write("                            <p></p>\r\n");
      out.write("                            <h3></h3>\r\n");
      out.write("                            <div class=\"explorer_europe\">\r\n");
      out.write("                                <div class=\"container back-white\">\r\n");
      out.write("                                    <div class=\"explorer_wrap \">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-4\">\r\n");
      out.write("                                                <h3></h3>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-8\">\r\n");
      out.write("                                                <div class=\"explorer_tab\">\r\n");
      out.write("                                                    <nav>\r\n");
      out.write("                                                        <div class=\"nav\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("                                                            <a class=\"nav-item nav-link  active\" id=\"nav-home-tab\" data-toggle=\"tab\"\r\n");
      out.write("                                                                href=\"#nav-home\" role=\"tab\" aria-controls=\"nav-home\"\r\n");
      out.write("                                                                aria-selected=\"true\">Freelancer</a>\r\n");
      out.write("                                                            <a class=\"nav-item nav-link\" id=\"nav-profile-tab\" data-toggle=\"tab\"\r\n");
      out.write("                                                                href=\"#nav-profile\" role=\"tab\" aria-controls=\"nav-profile\"\r\n");
      out.write("                                                                aria-selected=\"false\">Client</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </nav>\r\n");
      out.write("                        \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("                                        <div class=\"tab-pane fade show active\" id=\"nav-home\" role=\"tabpanel\" aria-labelledby=\"nav-home-tab\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-block btn-hei\" id=\"header-tab-btn\" \r\n");
      out.write("                                                    style=\"background-color: #212529;color: white;\">\r\n");
      out.write("                                                        Freelancer 찾기\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-block btn-hei\" id=\"header-tab-btn\" \r\n");
      out.write("                                                    style=\"background-color: #212529;color: white;\">\r\n");
      out.write("                                                        Freelancer 쓰기\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"tab-pane fade\" id=\"nav-profile\" role=\"tabpanel\" aria-labelledby=\"nav-profile-tab\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                     \r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-block btn-hei\" id=\"header-tab-btn\" \r\n");
      out.write("                                                    style=\"background-color: #212529;color: white;\">\r\n");
      out.write("                                                        Client 찾기\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                     \r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-block btn-hei\" id=\"header-tab-btn\" \r\n");
      out.write("                                                    style=\"background-color: #212529;color: white;\">\r\n");
      out.write("                                                        Client 쓰기\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slider_area_end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- <div class=\"header-padding\">\r\n");
      out.write("        <img src=\"img/case/1.png\">\r\n");
      out.write("    </div> -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"popular_catagory_area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-12\">\r\n");
      out.write("                    <div class=\"section_title mb-60 text-center\">\r\n");
      out.write("                        <p></p>\r\n");
      out.write("                        <h3>\r\n");
      out.write("                            Categories\r\n");
      out.write("                        </h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                <a href=\"Listings.html\"><h4>Amazing Places</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/2.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                <a href=\"Listings.html\"><h4>Concerts</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/3.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                    <a href=\"Listings.html\"><h4>Travel guide</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/4.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                    <a href=\"Listings.html\"><h4>Music Festival</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/5.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                    <a href=\"Listings.html\"><h4>Night Club</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/6.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                    <a href=\"Listings.html\"><h4>Bars & Pubs</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/7.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                    <a href=\"Listings.html\"><h4>Cafe</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 col-md-4 col-lg-3\">\r\n");
      out.write("                    <div class=\"single_catagory\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/catagory/8.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hover_overlay\">\r\n");
      out.write("                            <div class=\"hover_inner\">\r\n");
      out.write("                                    <a href=\"Listings.html\"><h4>Restaurants</h4></a>\r\n");
      out.write("                                <span>05 Listings</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- testimonial_area  -->\r\n");
      out.write("  <div class=\"testimonial_area  \">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl-12\">\r\n");
      out.write("                <div class=\"section_title mb-60 text-center\">\r\n");
      out.write("                    <p></p>\r\n");
      out.write("                    <h3>\r\n");
      out.write("                        Recently Registered Projects\r\n");
      out.write("\r\n");
      out.write("                    </h3>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl-12 \">\r\n");
      out.write("                <div class=\"testmonial_active owl-carousel height_testmonial\">\r\n");
      out.write("                    <div class=\"single_carousel \">\r\n");
      out.write("                        <div class=\"single_testmonial  \">                           \r\n");
      out.write("                            <div class=\"explorer_europe  \">\r\n");
      out.write("                                <div class=\"container \">                                    \r\n");
      out.write("                                    <div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("                                        <div class=\"tab-pane fade show active\" id=\"nav-home\" role=\"tabpanel\" aria-labelledby=\"nav-home-tab\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-xl-4 col-lg-4 col-md-6\">\r\n");
      out.write("                                                    <div class=\"single_explorer\">\r\n");
      out.write("                                                        <div class=\"thumb\">\r\n");
      out.write("                                                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/explorer/2.png\" alt=\"\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"explorer_bottom d-flex\">\r\n");
      out.write("                                                            <div class=\"icon\">\r\n");
      out.write("                                                                <i class=\"flaticon-food\"></i>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"explorer_info\">\r\n");
      out.write("                                                                <h3><a href=\"single_listings.html\">Freshly Food</a></h3>\r\n");
      out.write("                                                                <p>700/D, Kings road, Green lane, London</p>\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                                                        +10 278 367 9823</li>\r\n");
      out.write("                                                                    <li><i class=\"fa fa-envelope\"></i> contact@midnight.com</li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-xl-4 col-lg-4 col-md-6\">\r\n");
      out.write("                                                    <div class=\"single_explorer\">\r\n");
      out.write("                                                        <div class=\"thumb\">\r\n");
      out.write("                                                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/explorer/2.png\" alt=\"\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"explorer_bottom d-flex\">\r\n");
      out.write("                                                            <div class=\"icon\">\r\n");
      out.write("                                                                <i class=\"flaticon-food\"></i>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"explorer_info\">\r\n");
      out.write("                                                                <h3><a href=\"single_listings.html\">Freshly Food</a></h3>\r\n");
      out.write("                                                                <p>700/D, Kings road, Green lane, London</p>\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                                                        +10 278 367 9823</li>\r\n");
      out.write("                                                                    <li><i class=\"fa fa-envelope\"></i> contact@midnight.com</li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-xl-4 col-lg-4 col-md-6\">\r\n");
      out.write("                                                    <div class=\"single_explorer\">\r\n");
      out.write("                                                        <div class=\"thumb\">\r\n");
      out.write("                                                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/explorer/3.png\" alt=\"\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"explorer_bottom d-flex\">\r\n");
      out.write("                                                            <div class=\"icon\">\r\n");
      out.write("                                                                <i class=\"flaticon-food-1\"></i>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"explorer_info\">\r\n");
      out.write("                                                                <h3><a href=\"single_listings.html\">Midnight</a></h3>\r\n");
      out.write("                                                                <p>700/D, Kings road, Green lane, London</p>\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                                                        +10 278 367 9823</li>\r\n");
      out.write("                                                                    <li><i class=\"fa fa-envelope\"></i> contact@midnight.com</li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"single_carousel\">\r\n");
      out.write("                        <div class=\"single_testmonial \">\r\n");
      out.write("                            <div class=\"explorer_europe  \">\r\n");
      out.write("                                <div class=\"container \">                                    \r\n");
      out.write("                                    <div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("                                        <div class=\"tab-pane fade show active\" id=\"nav-home\" role=\"tabpanel\" aria-labelledby=\"nav-home-tab\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-xl-4 col-lg-4 col-md-6\">\r\n");
      out.write("                                                    <div class=\"single_explorer\">\r\n");
      out.write("                                                        <div class=\"thumb\">\r\n");
      out.write("                                                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/explorer/2.png\" alt=\"\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"explorer_bottom d-flex\">\r\n");
      out.write("                                                            <div class=\"icon\">\r\n");
      out.write("                                                                <i class=\"flaticon-food\"></i>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"explorer_info\">\r\n");
      out.write("                                                                <h3><a href=\"single_listings.html\">Freshly Food</a></h3>\r\n");
      out.write("                                                                <p>700/D, Kings road, Green lane, London</p>\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                                                        +10 278 367 9823</li>\r\n");
      out.write("                                                                    <li><i class=\"fa fa-envelope\"></i> contact@midnight.com</li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-xl-4 col-lg-4 col-md-6\">\r\n");
      out.write("                                                    <div class=\"single_explorer\">\r\n");
      out.write("                                                        <div class=\"thumb\">\r\n");
      out.write("                                                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/explorer/2.png\" alt=\"\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"explorer_bottom d-flex\">\r\n");
      out.write("                                                            <div class=\"icon\">\r\n");
      out.write("                                                                <i class=\"flaticon-food\"></i>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"explorer_info\">\r\n");
      out.write("                                                                <h3><a href=\"single_listings.html\">Freshly Food</a></h3>\r\n");
      out.write("                                                                <p>700/D, Kings road, Green lane, London</p>\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                                                        +10 278 367 9823</li>\r\n");
      out.write("                                                                    <li><i class=\"fa fa-envelope\"></i> contact@midnight.com</li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-xl-4 col-lg-4 col-md-6\">\r\n");
      out.write("                                                    <div class=\"single_explorer\">\r\n");
      out.write("                                                        <div class=\"thumb\">\r\n");
      out.write("                                                            <img src=\"");
      out.print(ResourcePath.path );
      out.write("/img/explorer/3.png\" alt=\"\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"explorer_bottom d-flex\">\r\n");
      out.write("                                                            <div class=\"icon\">\r\n");
      out.write("                                                                <i class=\"flaticon-food-1\"></i>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"explorer_info\">\r\n");
      out.write("                                                                <h3><a href=\"single_listings.html\">Midnight</a></h3>\r\n");
      out.write("                                                                <p>700/D, Kings road, Green lane, London</p>\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                                                        +10 278 367 9823</li>\r\n");
      out.write("                                                                    <li><i class=\"fa fa-envelope\"></i> contact@midnight.com</li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /testimonial_area  -->\r\n");
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("    <!-- footer start -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("      <div class=\"footer_top\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xl-4 col-md-6 col-lg-3\" >\r\n");
      out.write("                      <div class=\"footer_widget\">\r\n");
      out.write("                          <div class=\"footer_logo\">\r\n");
      out.write("                              <a href=\"#\">\r\n");
      out.write("                                  <img src=\"http://localhost:8080/searchfree/resources/img/footer_logo.png\" alt=\"\">\r\n");
      out.write("                              </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <p>\r\n");
      out.write("                              Esteem spirit temper too say adieus who <br> direct esteem. It esteems luckily or <br>\r\n");
      out.write("                              picture placing drawing.\r\n");
      out.write("                          </p>\r\n");
      out.write("                          <div class=\"socail_links\">\r\n");
      out.write("                              <ul>\r\n");
      out.write("                                  <li>\r\n");
      out.write("                                      <a href=\"#\">\r\n");
      out.write("                                          <i class=\"ti-facebook\"></i>\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li>\r\n");
      out.write("                                      <a href=\"#\">\r\n");
      out.write("                                          <i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li>\r\n");
      out.write("                                      <a href=\"#\">\r\n");
      out.write("                                          <i class=\"fa fa-twitter\"></i>\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li>\r\n");
      out.write("                                      <a href=\"#\">\r\n");
      out.write("                                          <i class=\"fa fa-instagram\"></i>\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-xl-2 col-md-6 col-lg-3\">\r\n");
      out.write("                      <div class=\"footer_widget\">\r\n");
      out.write("                          <h3 class=\"footer_title\">\r\n");
      out.write("                              Services\r\n");
      out.write("                          </h3>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li><a href=\"#\">SEO/SEM </a></li>\r\n");
      out.write("                              <li><a href=\"#\">Web design </a></li>\r\n");
      out.write("                              <li><a href=\"#\">Ecommerce</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Digital marketing</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-xl-2 col-md-6 col-lg-2\">\r\n");
      out.write("                      <div class=\"footer_widget\">\r\n");
      out.write("                          <h3 class=\"footer_title\">\r\n");
      out.write("                              Useful Links\r\n");
      out.write("                          </h3>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li><a href=\"#\">About</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                              <li><a href=\"#\"> Contact</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Support</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-xl-4 col-md-6 col-lg-4\">\r\n");
      out.write("                      <div class=\"footer_widget\">\r\n");
      out.write("                          <h3 class=\"footer_title\">\r\n");
      out.write("                              Subscribe\r\n");
      out.write("                          </h3>\r\n");
      out.write("                          <form action=\"#\" class=\"newsletter_form\">\r\n");
      out.write("                              <input type=\"text\" placeholder=\"Enter your mail\">\r\n");
      out.write("                              <button type=\"submit\">Subscribe</button>\r\n");
      out.write("                          </form>\r\n");
      out.write("                          <p class=\"newsletter_text\">Esteem spirit temper too say adieus who direct esteem esteems\r\n");
      out.write("                              luckily.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"copy-right_text\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("              <div class=\"footer_border\"></div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xl-12\">\r\n");
      out.write("                      <p class=\"copy_right text-center\">\r\n");
      out.write("                          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                      </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--/ footer end  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
